os: linux
arch: arm64

dist: focal

language: python
python:
  - '3.7'
  - '3.8'
  - '3.9'
  - '3.10'
  - '3.11'

install:
  - pip install setuptools==60.8.2
  - pip install -r requirements.txt
  - pip install .

script: pytest

deploy:
  provider: pypi
  user: __token__
  distributions: sdist bdist_wheel
  skip_existing: true
  edge: true
  on:
    python: 3.11
    tags: true
