os: linux
arch: arm64

dist: focal

language: python
python:
  - '3.8'
  - '3.9'
  - '3.10'
  - '3.11'
  - '3.12'
  - '3.13'

install:
  - pip install setuptools==80.3.1
  - pip install -r requirements.txt
  - pip install .

script: pytest

deploy:
  provider: pypi
  user: __token__
  distributions: sdist bdist_wheel
  skip_existing: true
  edge: true
  on:
    python: 3.13
    tags: true
